### PR TITLE
Update to 1.20.4

### PR DESCRIPTION
**Pull request by MiraculixxT**
Update all mixins and implementation to latest version, skipping 1.20.3. 

Not ready to merge yet, CommandFunctionMixin mixin server side needs to be fixed before.

### CODE REVIEW

**Comment by MiraculixxT** [comment]
Maybe someone with better knowledge about Mixins needs to look into the CommandFunctionMixin class

**Comment by sydist** [comment]
haha, i was also looking into this on my own, didnt realize someone else got stuck on that Mixin file

**Comment by sydist** [comment]
I'm not really a Mixin guy either, I got stuck on the same thing in my own fork, but maybe I can find something here, I'll look into it

**Comment by sydist** [comment]
hey, I believe I fixed the problem, it seems the server mixins were running on both the client and the server.
I made a pull request on your fork, please check it out! @MiraculixxT

**Comment by MiraculixxT** [comment]
I thought that fixed it, but its only pushing the error to server side. The mod will not longer work on single player and dedicated server will still fail

**Comment by sydist** [comment]
huh, weird, I was just using a build on my singe player testing world just fine.
unless you mean when it's open to LAN.

**Comment by arm32x** [comment]
The mixins should be running on both integrated servers (which are part of the client) and dedicated servers, so running them on the client is fine. There must be something else wrong with the mixin that causes it to fail. I'll take a look at it soon.

**Comment by arm32x** [comment]
After investigating a bit, I found that `CommandFunction` has been changed to an interface, which causes a mixin error since `CommandFunctionMixin` is a class. This appears to have been done to support the new function macros feature. I think macros were also part of 1.20.2, but I guess they changed the code a bit more since then.

It seems like `CommandFunctionMixin` will be tricky to upgrade since it adds a field to the class, which is not allowed in interfaces. This field saves the original lines of the `.mcfunction` file as Minecraft is parsing it so they can be sent to the client for editing later. However, I think it might be better to just read the file on-demand.

I'm planning to make a new branch based on this PR and start working on that soon. However, I'd like to keep a linear history in this repository (no merge commits), so I'll probably base the new branch on commit 8ba5e03f2ade21f91cad242940814b78ccc22930 instead of 83fedd9462c2eca8cc5cb1a8a630857b6b986e28.

**Comment by arm32x** [comment]
As of commit 9885bcd1b71477e67a53e7a8738a6d880f56d8c9, I have manually rebased and merged this PR (without the merge commit) and finished implementing the new function loading mechanism. However, GitHub doesn't recognize it as merged, so I'm closing it.

Thanks for your contribution!

**Pull request closed without merging**
